# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecf6c9ec6b9751230b2d4eeb1aa4aa0a84733a5eaa5d2993b1123a7959736ff5f797cc3073443a4daab15d798d74b85f09c62234446754a6e1e190d8702a1c42

test:
  secret_key_base: 6f47db1bc7919cc7efec9f59211c490639b4e80f633797f8156caeb121fd69ad7f3b186287a2ab00bf3f227af0221c9c79b13daa69543f498fc4432117d2be8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
